# Generated by Django 3.0.8 on 2021-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0003_remove_recipe_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(default='salt', max_length=200),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
